version: '3'
services:
  client:
    build: "react/pokedex"

    ports:
      - "3000:3000"
    depends_on:
      - "server"
    image: chokhonelidze/client:latest
    environment:
      - REACT_APP_SERVER=http://localhost:4000

  server: 
    build: "backend"
    ports:
      - "4000:4000"
    image: chokhonelidze/backend:latest
    environment:
      - DB=mongodb://mongo:27017/app_development
      - WEB_SERVER=http://localhost:3000
    depends_on:
      - mongo
    links:
      - mongo
  mongo:
    image: mongo
    ports: 
      - "27017:27017"